### ISSUE TITLE
Possible typo on USA participation at risk analysis: "Latinx"

### ISSUE THREAD

**Issue by tmfrnz** [HumanRightsMeasurementInitiative/hrmi-dataportal-content#171]
"Latinx" should likely be "Latin"?
https://github.com/HumanRightsMeasurementInitiative/hrmi-dataportal-content/blob/master/_posts/at-risk/participation/0100-01-01-USA.md

**Comment by annemariebrook** [comment]
No it's not a typo. Latinx is an inclusive term for people from Latin America
https://en.wikipedia.org/wiki/Latinx
